### ISSUE TITLE
Fail to resolve path with "." on Windows

### ISSUE THREAD

**Issue by xuehongyanL** [ginkgoch/node-shapefile-viewer#41]
**Platform**
windows

**Reproduce**
My shapefiles are in the folder "D:\china-latest-free.shp\"
When loading "gis_osm_buildings_a_free_1.shp" by  "File>Open Shp":

"gis_osm_buildings_a_free_1.shp, gis_osm_buildings_a_free_1.shp cannot found."

It works when I rename the folder as "D:\china-latest-free-shp\"

**Comment by xuehongyanL** [comment]
#42

**Comment by ginkgoch** [comment]
@xuehongyanL I release a new version with your fix. Thanks a lot!
